apiVersion: v1
kind: Service
metadata:
  name: galera
  labels:
    {{- include "galera.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    app.kubernetes.io/name: galera
    app.kubernetes.io/instance: {{ .Release.Name }}
