apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb
  labels:
    {{- include "lb.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lb
            port:
              number: 80
