apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-balancer
  labels:
    {{- include "lb.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
  - host: load-balancer-ko-medya.cloud.okteto.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lb
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lb
            port:
              name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: galera
  labels:
    {{- include "galera.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: galera
            port:
              name: mysql
