apiVersion: v1
kind: Service
metadata:
  name: lb
  labels:
    {{- include "lb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: lb
    app.kubernetes.io/instance: {{ .Release.Name }}
