name: ko-medya-cluster
build:
  lb:
    context: lb
    dockerfile: lb/Dockerfile
  galera:
    context: galera
    dockerfile: galera/Dockerfile
  app:
    context: app
    dockerfile: app/Dockerfile